In [1]:
!pip3 install pandas numpy matplotlib seaborn scikit-learn

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (2.3.3)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (2.4.0)
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.10.8)
Requirement already satisfied: seaborn in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (0.13.2)
Requirement already satisfied: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/kieraniphone/Library/Python/3.14/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /Users/kieraniphone/Library/Python/3.14/lib/python/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (12.1.0)
Requirement already satisfied: pyparsing>=3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (3.3.1)
Requirement already satisfied: scipy>=1.10.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /Users/kieraniphone/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip

In [2]:
import pandas as pd
import numpy as np

In [218]:
parking_permit_blocks = pd.read_csv(r'../data/residential_parking_permit_blocks.csv')
street_nodes = pd.read_csv(r'../data/Street_Nodes.csv')
street_centerlines = pd.read_csv(r'../data/Street_Centerline.csv')
#N/S North Side
#S/S South Side
#E/S East Side
#W/S West Side
#B/S Both Sides

In [219]:
street_centerlines

,fnode_,tnode_,lpoly_,rpoly_,length,stcl2_,stcl2_id,pre_dir,st_name,st_type,suf_dir,zip_left,zip_right,l_f_add,l_t_add,r_f_add,r_t_add,st_code,l_hundred,r_hundred,seg_id,oneway,class,responsibl,update_,newsegdate,multi_rep,streetlabe,stname,objectid,Shape__Length
0,26705,26716,NaN,NaN,2862.844615,NaN,NaN,,BARTRAM,AVE,,19153,19153,9200,9298,9201.0,9299.0,16120,9200,9200,100002,B,2,STATE,2004/05/18 00:00:00+00,NaN,0.0,BARTRAM AVE,BARTRAM AVE,1,1137.344551
1,26699,26704,NaN,NaN,935.023163,NaN,NaN,,BARTRAM,AVE,,19153,19153,9100,9198,9101.0,9199.0,16120,9100,9100,100003,B,2,STATE,1998/07/09 00:00:00+00,NaN,0.0,BARTRAM AVE,BARTRAM AVE,2,371.888030
2,26704,26705,NaN,NaN,122.512608,NaN,NaN,,BARTRAM,AVE,,19153,19153,0,0,0.0,0.0,16120,0,0,100004,B,2,STATE,1998/07/09 00:00:00+00,NaN,0.0,BARTRAM AVE,BARTRAM AVE,3,48.720227
3,26658,26672,NaN,NaN,735.818883,NaN,NaN,,EASTWICK,PL,,19153,19153,8500,8598,8501.0,8599.0,30570,8500,8500,100006,B,5,CITY,1998/07/09 00:00:00+00,NaN,0.0,EASTWICK PL,EASTWICK PL,4,292.693856
4,26653,26668,NaN,NaN,735.209140,NaN,NaN,,HARLEY,PL,,19153,19153,8500,8598,8501.0,8599.0,40570,8500,8500,100007,B,5,CITY,2006/04/07 00:00:00+00,NaN,0.0,HARLEY PL,HARLEY PL,5,292.440377
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41266,29254,29256,NaN,NaN,264.822078,NaN,NaN,,SUNFLOWER,DR,,19116,19116,15132,15146,15133.0,15147.0,75477,15100,15100,1180101,B,5,CITY,2011/08/30 00:00:00+00,2008/02/28 00:00:00+00,0.0,SUNFLOWER DR,SUNFLOWER DR,41267,105.595306
41267,29256,29259,NaN,NaN,159.663507,NaN,NaN,,SUNFLOWER,DR,,19116,19116,15148,15152,15149.0,15153.0,75477,15100,15100,1180102,B,5,CITY,2011/08/30 00:00:00+00,2008/02/28 00:00:00+00,0.0,SUNFLOWER DR,SUNFLOWER DR,41268,63.661475
41268,29259,29258,NaN,NaN,218.496317,NaN,NaN,,MIMOSA,DR,,19116,19116,2601,2699,2600.0,2698.0,56360,2600,2600,1180103,B,5,CITY,2011/08/30 00:00:00+00,2008/02/28 00:00:00+00,0.0,MIMOSA DR,MIMOSA DR,41269,87.173485
41269,29259,29260,NaN,NaN,228.896914,NaN,NaN,,SUNFLOWER,DR,,19116,19116,15154,15198,15155.0,15199.0,75477,15100,15100,1180104,B,5,CITY,2011/08/30 00:00:00+00,2008/02/28 00:00:00+00,0.0,SUNFLOWER DR,SUNFLOWER DR,41270,91.299361
41270,29261,29260,NaN,NaN,390.822828,NaN,NaN,,BLUEBELL,CT,,19116,19116,2601,2699,2600.0,2698.0,18050,2600,2600,1180105,B,5,CITY,2011/08/30 00:00:00+00,2008/02/28 00:00:00+00,0.0,BLUEBELL CT,BLUEBELL CT,41271,155.870463

In [ ]:
pd.set_option('display.max_columns', None)
parking_permit_blocks
street_nodes

np.int64(30213)

In [196]:
pd.set_option('display.max_columns', None)
complete_streets = pd.read_csv(r'../data/CompleteStreets.csv')
complete_streets.TNODE.max()

np.float64(25133.0)

In [244]:
street_centerlines.head()

,fnode_,tnode_,lpoly_,rpoly_,length,stcl2_,stcl2_id,pre_dir,st_name,st_type,suf_dir,zip_left,zip_right,l_f_add,l_t_add,r_f_add,r_t_add,st_code,l_hundred,r_hundred,seg_id,oneway,class,responsibl,update_,newsegdate,multi_rep,streetlabe,stname,objectid,Shape__Length
0,26705,26716,NaN,NaN,2862.844615,NaN,NaN,,BARTRAM,AVE,,19153,19153,9200,9298,9201.0,9299.0,16120,9200,9200,100002,B,2,STATE,2004/05/18 00:00:00+00,NaN,0.0,BARTRAM AVE,BARTRAM AVE,1,1137.344551
1,26699,26704,NaN,NaN,935.023163,NaN,NaN,,BARTRAM,AVE,,19153,19153,9100,9198,9101.0,9199.0,16120,9100,9100,100003,B,2,STATE,1998/07/09 00:00:00+00,NaN,0.0,BARTRAM AVE,BARTRAM AVE,2,371.888030
2,26704,26705,NaN,NaN,122.512608,NaN,NaN,,BARTRAM,AVE,,19153,19153,0,0,0.0,0.0,16120,0,0,100004,B,2,STATE,1998/07/09 00:00:00+00,NaN,0.0,BARTRAM AVE,BARTRAM AVE,3,48.720227
3,26658,26672,NaN,NaN,735.818883,NaN,NaN,,EASTWICK,PL,,19153,19153,8500,8598,8501.0,8599.0,30570,8500,8500,100006,B,5,CITY,1998/07/09 00:00:00+00,NaN,0.0,EASTWICK PL,EASTWICK PL,4,292.693856
4,26653,26668,NaN,NaN,735.209140,NaN,NaN,,HARLEY,PL,,19153,19153,8500,8598,8501.0,8599.0,40570,8500,8500,100007,B,5,CITY,2006/04/07 00:00:00+00,NaN,0.0,HARLEY PL,HARLEY PL,5,292.440377

In [246]:
testing = pd.merge(street_centerlines,street_nodes[['X','Y','intersecti','node_id']],left_on=['fnode_'],right_on='node_id',validate='many_to_one',how='left')

In [247]:
testing.X.isna().sum()

np.int64(0)

In [212]:
street_nodes.sort_values('node_id')

,X,Y,objectid,arc_,streetcl_,streetcl_i,node_id,int_id,update_,intersecti,x_coord,y_coord
22666,-8.350628e+06,4.886007e+06,22667,NaN,NaN,NaN,1,1,2000/01/03 00:00:00+00,COUNTY LINE RD,NaN,NaN
22636,-8.350584e+06,4.885972e+06,22637,NaN,NaN,NaN,2,2,1998/09/30 00:00:00+00,COUNTY LINE RD & WEXFORD PL,NaN,NaN
22638,-8.350507e+06,4.885910e+06,22639,NaN,NaN,NaN,3,3,1998/09/30 00:00:00+00,COUNTY LINE RD & OVERHILL AVE,NaN,NaN
22637,-8.350759e+06,4.885792e+06,22638,NaN,NaN,NaN,4,4,1998/09/30 00:00:00+00,WEXFORD PL & CUL DE SAC SOUTH,NaN,NaN
22639,-8.350340e+06,4.885777e+06,22640,NaN,NaN,NaN,5,5,1998/09/30 00:00:00+00,BUXMONT ST & COUNTY LINE RD,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
25596,-8.352965e+06,4.869284e+06,25597,NaN,NaN,NaN,30209,30209,2026/01/16 10:04:41+00,SB DELAWARE EXPY,NaN,NaN
25597,-8.364182e+06,4.874956e+06,25598,NaN,NaN,NaN,30210,30210,2026/01/16 11:16:01+00,OLD YORK RD,NaN,NaN
25598,-8.372243e+06,4.860246e+06,25599,NaN,NaN,NaN,30211,30211,2026/02/06 07:33:29+00,BUSTI ST & MANDELA WAY,NaN,NaN
25599,-8.372484e+06,4.860181e+06,25600,NaN,NaN,NaN,30212,30212,2026/02/06 08:03:29+00,N MELVILLE ST & SAINT MALACHYS WAY,NaN,NaN
25600,-8.372455e+06,4.860286e+06,25601,NaN,NaN,NaN,30213,30213,2026/02/06 08:12:04+00,N MELVILLE ST & MANDELA WAY,NaN,NaN

In [ ]:
complete_streets[complete_streets.]

In [206]:
testing[testing.X.isna()]

,OBJECTID,FNODE,TNODE,LENGTH,STCL2,STCL2_ID,PRE_DIR,ST_NAME,ST_TYPE,SEG_ID,ONEWAY,CLASS,STNAME,CLASS1,SPEEDLIM,RECSIGN,SURFAWIDTH,RECFACIL,PARKING,BIKENETWOR,LENGTH_MIL,PHASE2_SID,SIDEWALK_I,COMBINED_S,STREET_TYP,SIDEWLK_WD,WLK_ZN,Shape__Length,X,Y,intersecti,node_id
11,12,2720.0,2730.0,223.215751,4199.0,7692.0,NaN,CECIL B MOORE,AVE,520450,B,3.0,CECIL B MOORE AVE,Minor Arterial,30,Yes,32.0,Marked Shared Lane,B,YES,0.042276,Yes,1722.0,Urban Arterial,Urban Arterial,Greater than or equal to 12 feet,Greater than or equal to 6 feet,88.674905,NaN,NaN,NaN,NaN
14,15,635.0,641.0,200.350640,919.0,85555.0,NaN,POPLAR,ST,421061,B,4.0,POPLAR ST,Collector Residential,25,NaN,0.0,Marked Shared Lane,Z,YES,0.037945,Yes,13636.0,City Neighborhood Street,City Neighborhood Street,Greater than or equal to 12 feet,Greater than or equal to 6 feet,79.582746,NaN,NaN,NaN,NaN
99,100,126.0,121.0,221.180907,163.0,86025.0,N,15TH,ST,421535,TF,4.0,N 15TH ST,Collector Residential,25,Yes,0.0,Bike Friendly Street,Z,YES,0.041890,Yes,10401.0,City Neighborhood Street,City Neighborhood Street,Greater than or equal to 12 feet,Greater than or equal to 6 feet,88.184024,NaN,NaN,NaN,NaN
109,110,202.0,203.0,168.401098,287.0,86275.0,NaN,FAIRMOUNT,AVE,421788,B,3.0,FAIRMOUNT AVE,Minor Arterial,30,Yes,45.0,Bike Lanes,B,YES,0.031894,Yes,5303.0,Walkable Commercial Corridors,Walkable Commercial Corridors,Greater than or equal to 12 feet,Greater than or equal to 6 feet,66.880785,NaN,NaN,NaN,NaN
111,112,43.0,42.0,100.651672,48.0,86284.0,N,21ST,ST,421797,TF,4.0,N 21ST ST,Collector Residential,25,NaN,0.0,Bike Friendly Street,Z,YES,0.019063,Yes,10958.0,City Neighborhood Street,City Neighborhood Street,Greater than or equal to 12 feet,Greater than or equal to 6 feet,40.124831,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40601,40602,7951.0,23872.0,497.037486,35946.0,4418.0,NaN,HARLEY,DR,322856,B,5.0,HARLEY DR,Local Residential,25,NaN,0.0,NaN,Z,NaN,0.094136,NaN,0.0,Lower Density Residential,Lower Density Residential,Greater than or equal to 10 feet,Greater than or equal to 5 feet,197.900575,NaN,NaN,NaN,NaN
40604,40605,7009.0,7880.0,580.875383,38923.0,81254.0,NaN,SHIELDS,ST,200457,FT,5.0,SHIELDS ST,Local Residential,25,NaN,0.0,NaN,R,NaN,0.110014,NaN,0.0,Local (Catch All),Local (Catch All),Greater than or equal to 10 feet,Greater than or equal to 5 feet,231.035905,NaN,NaN,NaN,NaN
40612,40613,24279.0,19443.0,122.642153,36879.0,11638.0,NaN,HARBISON,AVE,762705,B,2.0,HARBISON AVE,Major Arterial,30 - 35,NaN,0.0,NaN,N,NaN,0.023228,Yes,6458.0,Urban Arterial,Urban Arterial,Greater than or equal to 12 feet,Greater than or equal to 6 feet,48.948093,NaN,NaN,NaN,NaN
40614,40615,24192.0,10668.0,81.055792,36641.0,6903.0,NaN,FITZWATER,ST,342213,FT,4.0,FITZWATER ST,Collector Residential,25,NaN,0.0,Bike Lanes,Z,YES,0.015351,No,0.0,City Neighborhood Street,City Neighborhood Street,Greater than or equal to 12 feet,Greater than or equal to 6 feet,32.181460,NaN,NaN,NaN,NaN
40634,40635,11220.0,11226.0,5429.300259,37456.0,7529.0,NB,DELAWARE,EXP,342542,FT,1.0,NB DELAWARE EXP,Expressway,NaN,NaN,0.0,NaN,N,NaN,1.028277,NaN,0.0,No Classification,N/A Interstate,NaN,NaN,2163.471707,NaN,NaN,NaN,NaN

In [6]:
def get_valid_optins(df,column):
    print(df[column].value_counts())

In [7]:
get_valid_optins(complete_streets,'STREET_TYP')

STREET_TYP
City Neighborhood Street               13341
Local (Catch All)                      11934
Lower Density Residential               6689
Urban Arterial                          5675
Walkable Commercial Corridors            816
Auto Oriented Commercial/Industrial      552
Shared Narrow                            479
N/A Interstate                           426
Civic/Ceremonial Street                  208
Scenic Drive                             124
Park Road                                121
High Volume Pedestrian                   117
Delete                                   108
Pedestrian-Access Only                    69
Name: count, dtype: int64

In [ ]:
from collections import defaultdict
class Node: 
    def __init__(self, id,intersection):
        self.id = int(id)

        
class Edge:
    def __init__(self, from_node, to_node, length, stname, oneway):
        self.from_node = from_node
        self.to_node = to_node
        self.length = length
        self.stname = stname
        self.oneway = oneway

class Graph:
    def __init__(self):
        self.nodes = {}
        self.edges = []
        self.adjacency = {}

    def get_node(self,node_id: int):
        
        if node_id not in self.nodes:
            self.nodes[node_id] = Node(node_id)
        return self.nodes[node_id]
    def add_edge(self, 
                 from_node_id,
                   to_node_id, 
                   length, 
                   stname, 
                   oneway):
        from_node = self.get_or_create_node(from_node_id)
        to_node = self.get_or_create_node(to_node_id)
        edge = Edge(from_node = from_node,
                        to_node =  to_node, 
                        length = length,  
                        stname = stname,
                        oneway = oneway)
        self.edges.append(edge)
    def build_adjacency(self):
        adjacency = defaultdict(list)
        for edge in self.edges:
            adjacency[edge.from_node].append(edge)
        self.adjacency=adjacency
    def show_node_adjacency(self, node_id):
        rows = []
        node = self.nodes.get(node_id,'')
        for edge in self.adjacency.get(node, []):
            rows.append({
            "from_node": edge.from_node.id,
            "to_node": edge.to_node.id,
            "street_name": edge.stname,
            "length": edge.length,
            "oneway": edge.oneway,
        })
        return pd.DataFrame(rows)

In [237]:
philly_streets = Graph()
philly_streets.get_or_create_node(1)

In [238]:
street_centerlines

,fnode_,tnode_,lpoly_,rpoly_,length,stcl2_,stcl2_id,pre_dir,st_name,st_type,suf_dir,zip_left,zip_right,l_f_add,l_t_add,r_f_add,r_t_add,st_code,l_hundred,r_hundred,seg_id,oneway,class,responsibl,update_,newsegdate,multi_rep,streetlabe,stname,objectid,Shape__Length
0,26705,26716,NaN,NaN,2862.844615,NaN,NaN,,BARTRAM,AVE,,19153,19153,9200,9298,9201.0,9299.0,16120,9200,9200,100002,B,2,STATE,2004/05/18 00:00:00+00,NaN,0.0,BARTRAM AVE,BARTRAM AVE,1,1137.344551
1,26699,26704,NaN,NaN,935.023163,NaN,NaN,,BARTRAM,AVE,,19153,19153,9100,9198,9101.0,9199.0,16120,9100,9100,100003,B,2,STATE,1998/07/09 00:00:00+00,NaN,0.0,BARTRAM AVE,BARTRAM AVE,2,371.888030
2,26704,26705,NaN,NaN,122.512608,NaN,NaN,,BARTRAM,AVE,,19153,19153,0,0,0.0,0.0,16120,0,0,100004,B,2,STATE,1998/07/09 00:00:00+00,NaN,0.0,BARTRAM AVE,BARTRAM AVE,3,48.720227
3,26658,26672,NaN,NaN,735.818883,NaN,NaN,,EASTWICK,PL,,19153,19153,8500,8598,8501.0,8599.0,30570,8500,8500,100006,B,5,CITY,1998/07/09 00:00:00+00,NaN,0.0,EASTWICK PL,EASTWICK PL,4,292.693856
4,26653,26668,NaN,NaN,735.209140,NaN,NaN,,HARLEY,PL,,19153,19153,8500,8598,8501.0,8599.0,40570,8500,8500,100007,B,5,CITY,2006/04/07 00:00:00+00,NaN,0.0,HARLEY PL,HARLEY PL,5,292.440377
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41266,29254,29256,NaN,NaN,264.822078,NaN,NaN,,SUNFLOWER,DR,,19116,19116,15132,15146,15133.0,15147.0,75477,15100,15100,1180101,B,5,CITY,2011/08/30 00:00:00+00,2008/02/28 00:00:00+00,0.0,SUNFLOWER DR,SUNFLOWER DR,41267,105.595306
41267,29256,29259,NaN,NaN,159.663507,NaN,NaN,,SUNFLOWER,DR,,19116,19116,15148,15152,15149.0,15153.0,75477,15100,15100,1180102,B,5,CITY,2011/08/30 00:00:00+00,2008/02/28 00:00:00+00,0.0,SUNFLOWER DR,SUNFLOWER DR,41268,63.661475
41268,29259,29258,NaN,NaN,218.496317,NaN,NaN,,MIMOSA,DR,,19116,19116,2601,2699,2600.0,2698.0,56360,2600,2600,1180103,B,5,CITY,2011/08/30 00:00:00+00,2008/02/28 00:00:00+00,0.0,MIMOSA DR,MIMOSA DR,41269,87.173485
41269,29259,29260,NaN,NaN,228.896914,NaN,NaN,,SUNFLOWER,DR,,19116,19116,15154,15198,15155.0,15199.0,75477,15100,15100,1180104,B,5,CITY,2011/08/30 00:00:00+00,2008/02/28 00:00:00+00,0.0,SUNFLOWER DR,SUNFLOWER DR,41270,91.299361
41270,29261,29260,NaN,NaN,390.822828,NaN,NaN,,BLUEBELL,CT,,19116,19116,2601,2699,2600.0,2698.0,18050,2600,2600,1180105,B,5,CITY,2011/08/30 00:00:00+00,2008/02/28 00:00:00+00,0.0,BLUEBELL CT,BLUEBELL CT,41271,155.870463

In [240]:
for ind, data in street_centerlines[(street_centerlines.oneway.str.strip() != '')].iterrows():
    fnode = data.fnode_
    tnode = data.tnode_
    length = data.length
    stname = data.stname
    oneway = data.oneway
    if oneway == 'B':
        philly_streets.add_edge(from_node_id=fnode,
                                to_node_id=tnode,
                                length=length,
                                stname = stname,
                                oneway=oneway)
        philly_streets.add_edge(from_node_id=tnode,
                                to_node_id=fnode,
                                length=length,
                                stname = stname,
                                oneway=oneway)
    elif oneway == 'TF':
        philly_streets.add_edge(from_node_id=tnode,
                                to_node_id=fnode,
                                length=length,
                                stname = stname,
                                oneway=oneway)
    elif oneway == 'FT':
        philly_streets.add_edge(from_node_id=fnode,
                                to_node_id=tnode,
                                length=length,
                                stname = stname,
                                oneway=oneway)

In [241]:
philly_streets.build_adjacency()

In [242]:
x = philly_streets.show_node_adjacency(3)

In [243]:
x

   from_node  to_node     street_name      length oneway
0          3        8    OVERHILL AVE  704.031771      B
1          3        2  COUNTY LINE RD  247.134114      B
2          3        5  COUNTY LINE RD  535.401468      B